; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.12 on Mon Sep 05 2022 16:49:54 GMT+1000 (Australian Eastern Standard Time)
M280 P0 S10 ; deploy BLTouch

